# Generated by Django 3.1.7 on 2021-04-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='plant',
        ),
    ]
