# Generated by Django 3.1.5 on 2021-01-31 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='humidity_limits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='humidity_limits', to='plants.planttolerancelimits'),
        ),
        migrations.AddField(
            model_name='plant',
            name='soilmoist_limits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soilmoist_limits', to='plants.planttolerancelimits'),
        ),
        migrations.AlterField(
            model_name='planttolerancelimits',
            name='alert_lower',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planttolerancelimits',
            name='alert_upper',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planttolerancelimits',
            name='warning_lower',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planttolerancelimits',
            name='warning_upper',
            field=models.IntegerField(null=True),
        ),
    ]
