# Generated by Django 3.1.7 on 2021-04-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_remove_device_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
