# Generated by Django 3.1.5 on 2021-02-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_eventhistory_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventhistory',
            options={'ordering': ['updated_at']},
        ),
    ]
