# Generated by Django 3.1.5 on 2021-02-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_auto_20210201_1255'),
        ('plants', '0005_auto_20210201_1335'),
    ]

    operations = [
    ]
