# Generated by Django 3.1.6 on 2021-02-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_eventhistory_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
