# Generated by Django 3.1.6 on 2021-02-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_plant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='ideal_soil_type',
            field=models.CharField(max_length=170, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='toxicity',
            field=models.CharField(max_length=170, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(max_length=170, null=True),
        ),
    ]
