# Generated by Django 3.1.6 on 2021-02-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_auto_20210207_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
