# Generated by Django 3.1.6 on 2021-02-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0011_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='image_url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
