# Generated by Django 3.1.6 on 2021-02-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_auto_20210208_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('image_url', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
