# Generated by Django 3.1.6 on 2021-02-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_auto_20210208_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantImage',
        ),
    ]
