# Generated by Django 3.1.6 on 2021-02-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_delete_plantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
